### ISSUE TITLE
Use case links should open new windows (?)

### ISSUE THREAD

**Issue by waxlamp** [girder/legacy-resonant-website#7]

**Comment by jeffbaumes** [comment]
I assume you mean the links in the use case descriptions, e.g. the link out to arbor.kitware.com. I think when we resolve #3, it will be ok to not open new windows, since the back button will correctly go back to the use case description, then you can go back again to the main page. When people are just trying things out and exploring, they probably don't want lots of browser tabs to appear.

**Comment by waxlamp** [comment]
On second though, I agree.  Especially since the user can choose to middle click, etc., on the "for more information" link.
